version: '2'
networks:
  back-tier:
    driver: bridge
services:
  rails_23923.app:
    build: .
    command: foreman start
    ports:
      - 5000:5000
    networks:
      - back-tier
    volumes:
      - .:/usr/src/app
      - rails_23923.volume:/usr/src/bundle
volumes:
  rails_23923.volume:
    driver: local
